[package]
name = "fake-propane"
version = "0.1.0"
authors = ["Without Boats <woboats@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core = "0.3.5"
